version: '3.9'

services:
  #DB service, runs postgress
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB : spoter
      PGDATA: /var/lib/postgresql/data
    volumes:
      - spoter-db-data:/var/lib/postgresql/data
    restart: unless-stopped
  #web server container
  webServer:
    build:
      context: .
      dockerfile: Dockerfile
    image: spoter-ws
    container_name: spoter-ws
    ports:
      - 5173:5173
      - 4173:4173
    depends_on:
      - postgres
    volumes:
      - ./src:/home/node/spoter/src
      - ./static:/home/node/spoter/static
      - ./__test__:/home/node/spoter/__test__
      - ./.babelrc:/home/node/spoter/.babelrc
      - ./svelte.config.js:/home/node/spoter/svelte.config.js
      - ./vite.config.js:/home/node/spoter/vite.config.js
      - ./playwright.config.js:/home/node/spoter/playwright.config.js
      - ./postcss.config.cjs:/home/node/spoter/postcss.config.cjs
      - ./tailwind.config.cjs:/home/node/spoter/tailwind.config.cjs
      - ./prisma/schema.prisma:/home/node/spoter/prisma/schema.prisma
      - ./.env:/home/node/spoter/.env
    entrypoint: sh ./entrypoint.sh
    restart: no

volumes:
  spoter-db-data: